name: Lint Shell Scripts

on:
  push:
    paths:
      - "*.sh"
      - "shadow"
  pull_request:
    paths:
      - "*.sh"
      - "shadow"

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run shellcheck
        run: shellcheck bootstrap.sh shadow
      - name: Syntax check
        run: bash -n bootstrap.sh shadow
